INSERT INTO public.exercises
  (name, muscle_group, difficulty, description, image_url)
VALUES
  ('Bench Press', 'Chest', 'intermediate', 'Press a barbell from the chest while lying on a flat bench.', NULL),
  ('Incline Dumbbell Press', 'Chest', 'intermediate', 'Press two dumbbells upward on an incline bench to target upper chest.', NULL),
  ('Push‑Up', 'Chest', 'beginner', 'Body‑weight press from the floor keeping torso rigid and elbows tucked.', NULL),
  ('Chest Fly', 'Chest', 'beginner', 'Open and close the arms in a wide arc on a bench to isolate pectorals.', NULL),
  ('Decline Bench Press', 'Chest', 'intermediate', 'Barbell press on a decline bench emphasizing lower chest fibres.', NULL),
  ('Pull‑Up', 'Back', 'advanced', 'Pronated‑grip vertical pull hanging from a bar to engage lats.', NULL),
  ('Bent‑Over Row', 'Back', 'intermediate', 'Row a barbell toward the torso with flat back and hinged hips.', NULL),
  ('Lat Pulldown', 'Back', 'beginner', 'Pull a cable bar from overhead to chest level while seated.', NULL),
  ('Seated Cable Row', 'Back', 'beginner', 'Row a narrow handle toward the abdomen while seated upright.', NULL),
  ('Deadlift', 'Back', 'advanced', 'Lift a loaded barbell from floor to hip level with neutral spine.', NULL),
  ('Overhead Press', 'Shoulders', 'intermediate', 'Press a barbell overhead from shoulder height standing tall.', NULL),
  ('Lateral Raise', 'Shoulders', 'beginner', 'Raise dumbbells out to the sides to shoulder height for delts.', NULL),
  ('Front Raise', 'Shoulders', 'beginner', 'Lift dumbbells forward to shoulder height targeting anterior delts.', NULL),
  ('Arnold Press', 'Shoulders', 'advanced', 'Rotate dumbbells from front rack to overhead in a continuous press.', NULL),
  ('Upright Row', 'Shoulders', 'intermediate', 'Pull a barbell vertically to upper chest with elbows high.', NULL),
  ('Bicep Curl', 'Arms', 'beginner', 'Flex elbows to lift a bar or dumbbells, isolating the biceps.', NULL),
  ('Triceps Pushdown', 'Arms', 'beginner', 'Extend elbows downward on a cable to work the triceps.', NULL),
  ('Hammer Curl', 'Arms', 'beginner', 'Curl dumbbells with neutral grip to emphasize brachialis.', NULL),
  ('Skull Crusher', 'Arms', 'intermediate', 'Lie on bench and extend EZ‑bar from forehead to full elbow lockout.', NULL),
  ('Dips', 'Arms', 'advanced', 'Lower and raise body on parallel bars focusing on triceps.', NULL),
  ('Squat', 'Legs', 'intermediate', 'Barbell back squat descending until thighs parallel to floor.', NULL),
  ('Leg Press', 'Legs', 'beginner', 'Push a sled upward with feet shoulder‑width apart.', NULL),
  ('Lunges', 'Legs', 'beginner', 'Step forward and lower until both knees are at 90° angles.', NULL),
  ('Romanian Deadlift', 'Legs', 'intermediate', 'Hinge at hips lowering bar to mid‑shin while keeping legs semi‑straight.', NULL),
  ('Leg Extension', 'Legs', 'beginner', 'Extend knees on machine isolating quadriceps.', NULL),
  ('Plank', 'Abs', 'beginner', 'Hold a straight‑body position on forearms and toes.', NULL),
  ('Crunch', 'Abs', 'beginner', 'Curl torso toward knees from supine position.', NULL),
  ('Hanging Leg Raise', 'Abs', 'intermediate', 'Raise legs to hip height while hanging from a bar.', NULL),
  ('Russian Twist', 'Abs', 'beginner', 'Rotate torso side to side holding a weight while seated.', NULL),
  ('Bicycle Crunch', 'Abs', 'beginner', 'Alternate elbow‑to‑knee crunches mimicking pedalling motion.', NULL),
  ('Hip Thrust', 'Glutes', 'intermediate', 'Drive hips upward resting upper back on bench with barbell over hips.', NULL),
  ('Glute Bridge', 'Glutes', 'beginner', 'Bridge hips off the floor squeezing glutes at top.', NULL),
  ('Bulgarian Split Squat', 'Glutes', 'advanced', 'Split squat with back foot elevated to isolate front‑leg glutes.', NULL),
  ('Kettlebell Swing', 'Glutes', 'intermediate', 'Hinge and snap hips to drive kettlebell to shoulder height.', NULL),
  ('Cable Kickback', 'Glutes', 'beginner', 'Extend leg backward against cable resistance targeting glutes.', NULL),
  ('Treadmill Run', 'Cardio', 'beginner', 'Continuous running on a treadmill at moderate speed.', NULL),
  ('Rowing Machine', 'Cardio', 'beginner', 'Full‑body rower strokes at steady cadence for endurance.', NULL),
  ('Cycling', 'Cardio', 'beginner', 'Pedal a stationary bike maintaining target heart rate.', NULL),
  ('Jump Rope', 'Cardio', 'beginner', 'Continuous rope skips to improve coordination and cardio.', NULL),
  ('Burpees', 'Cardio', 'intermediate', 'Squat‑thrust and jump combination performed at high pace.', NULL)
ON CONFLICT (lower(name)) DO NOTHING;
